export default [
	{path: '/Comp',name: 'comp',component(resolve) {require(['../views/comp/Comp.vue'], resolve)}},
	{path: '/CompColumn',name: 'compcolumn',component(resolve) {require(['../views/comp/CompColumn.vue'], resolve)}},
	{path: '/CompScroll',name: 'compscroll',component(resolve) {require(['../views/comp/CompScroll.vue'], resolve)}},
	{path: '/CompWrap',name: 'compwrap',component(resolve) {require(['../views/comp/CompWrap.vue'], resolve)}},
	{path: '/Game',name: 'game',component(resolve) {require(['../views/game/Game.vue'], resolve)}},
	{path: '/gArena',name: 'garena',component(resolve) {require(['../views/game/gArena.vue'], resolve)}},
	{path: '/gCamp',name: 'gcamp',component(resolve) {require(['../views/game/gCamp.vue'], resolve)}},
	{path: '/gFiled',name: 'gfiled',component(resolve) {require(['../views/game/gFiled.vue'], resolve)}},
	{path: '/gHeroEdit',name: 'gheroedit',component(resolve) {require(['../views/game/gHeroEdit.vue'], resolve)}},
	{path: '/gHeroList',name: 'gherolist',component(resolve) {require(['../views/game/gHeroList.vue'], resolve)}},
	{path: '/gMapEdit',name: 'gmapedit',component(resolve) {require(['../views/game/gMapEdit.vue'], resolve)}},
	{path: '/gMapList',name: 'gmaplist',component(resolve) {require(['../views/game/gMapList.vue'], resolve)}},
	{path: '/gShop',name: 'gshop',component(resolve) {require(['../views/game/gShop.vue'], resolve)}},
	{path: '/gStore',name: 'gstore',component(resolve) {require(['../views/game/gStore.vue'], resolve)}},
	{path: '/Home',name: 'home',component(resolve) {require(['../views/home/Home.vue'], resolve)}},
	{path: '/Login',name: 'login',component(resolve) {require(['../views/home/Login.vue'], resolve)}},
	{path: '/Resume',name: 'resume',component(resolve) {require(['../views/home/Resume.vue'], resolve)}},
	{path: '/TestNew',name: 'testnew',component(resolve) {require(['../views/home/TestNew.vue'], resolve)}},
	{path: '/mathine',name: 'mathine',component(resolve) {require(['../views/mathine/mathine.vue'], resolve)}},
	{path: '/MusicHome',name: 'musichome',component(resolve) {require(['../views/music/MusicHome.vue'], resolve)}},
	{path: '/LolYH',name: 'lolyh',component(resolve) {require(['../views/tuyi/LolYH.vue'], resolve)}},
	{path: '/LolYHMin',name: 'lolyhmin',component(resolve) {require(['../views/tuyi/LolYHMin.vue'], resolve)}}
]